baseURL = "https://cocky-stonebraker-a007c1.netlify.app/"
languageCode = "es-es"
title = "Trabecular"
theme = "trabecular"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
sectionPagesMenu = "main"

[menu]
    [[menu.main]]
    identifier = "news"
    name       = "News"
    url        = "/"
    weight     = 0

    [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = 1

    [[menu.main]]
    identifier = "portfolio"
    name       = "Portfolio"
    url        = "/portfolio/"
    weight     = 2

    [[menu.main]]
    identifier = "research"
    name       = "Research"
    url        = "/research/"
    weight     = 3

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 4

    [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags/"
    weight     = 5