baseURL = "https://trabecular.uy/"
languageCode = "es-es"
title = "Trabecular"
theme = "trabecular"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
sectionPagesMenu = "main"
googleAnalytics = "UA-180400680-1"