backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  site_url: https://cocky-stonebraker-a007c1.netlify.app/
  

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Paginas"
    files:
      - file: "content/_index.md"
        label: "Inicio"
        name: "inicio"
        fields:

          - label: "Video"
            name: Video
            widget: object
            fields: 
              - label: "Subtitulo"
                name: "subtitulo"
                widget: "text"
              - label: "Url"
                name: "url"
                widget: "string"

          - label: "Intro"
            name: Intro
            widget: list
            fields: 
              - label: Titulo
                name: titulo
                widget: string
              - label: "Items"
                name: "items"
                widget: "list"
                field: {label: "item", name: "item", widget: "string"}

          - label: "Trabajo"
            name: Trabajo
            widget: object
            fields: 
              - label: Titulo
                name: titulo
                widget: string
              - label: "Tarjetas"
                name: "tarjetas"
                widget: "list"
                fields: 
                  - {label: "titulo", name: "titulo", widget: "string"}
                  - {label: "icono", name: "icono", widget: "image"}
                  - {label: "texto", name: "texto", widget: "string"}

          - label: "Entrega"
            name: Entrega
            widget: list
            fields: 
              - label: titulo
                name: titulo
                widget: string
              - label: texto
                name: texto
                widget: string

          - label: "Equipo"
            name: Equipo
            widget: list
            fields: 
              - label: foto
                name: foto
                widget: image
              - label: nombre
                name: nombre
                widget: string
              - label: cargo
                name: cargo
                widget: string
              - label: descripcion
                name: descripcion
                widget: string
              - label: linkedin
                name: linkedin
                widget: string
                