backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  site_url: https://trabecular.uy/
  

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Paginas"
    files:
      # Pagina de inicio
      - file: "content/_index.md"
        label: "Inicio"
        name: "inicio"
        fields:

          - label: "Video"
            name: Video
            widget: object
            fields: 
              - label: "Subtitulo"
                name: "subtitulo"
                widget: "text"
              - label: "Url"
                name: "url"
                widget: "string"

          - label: "Intro"
            name: Intro
            widget: list
            fields: 
              - label: Titulo
                name: titulo
                widget: string
              - label: "Items"
                name: "items"
                widget: "list"
                field: {label: "item", name: "item", widget: "string"}

          - label: "Trabajo"
            name: Trabajo
            widget: object
            fields: 
              - label: Titulo
                name: titulo
                widget: string
              - label: "Tarjetas"
                name: "tarjetas"
                widget: "list"
                fields: 
                  - {label: "titulo", name: "titulo", widget: "string"}
                  - {label: "icono", name: "icono", widget: "image", default: "/img/"}
                  - {label: "texto", name: "texto", widget: "string"}

          - label: "Entrega"
            name: Entrega
            widget: list
            fields: 
              - label: titulo
                name: titulo
                widget: string
              - label: texto
                name: texto
                widget: string

          - label: "Equipo"
            name: Equipo
            widget: list
            fields: 
              - label: foto
                name: foto
                widget: image
              - label: nombre
                name: nombre
                widget: string
              - label: cargo
                name: cargo
                widget: string
              - label: descripcion
                name: descripcion
                widget: string
              - label: linkedin
                name: linkedin
                widget: string

  # Productos
  - name: "productos" # Used in routes, e.g., /admin/collections/blog
    label: "Productos" # Used in the UI
    folder: "content/productos/producto" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{titulo}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Producto", name: "producto", widget: "hidden", default: "productos"}
      - {label: "Titulo", name: "titulo", widget: "string"}
      - {label: "Descripcion", name: "descripcion", widget: "text"}
      - {label: "Indicaciones", name: "indicaciones", widget: "list", field: {label: "item", name: "item", widget: "string"}}
      - {label: "Galeria", name: "galeria", widget: "list", field: {label: "imagen", name: "imagen", widget: "image"}}

  
  # BLog
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{titulo}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Blog", name: "blog", widget: "hidden", default: "Blogs"}
      - {label: "Titulo", name: "titulo", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen", name: "imagen", widget: "image"}
      - {label: "Texto", name: "body", widget: "markdown"}
